Repository mapbox/mapbox-directions-swift, pull requests merged in 2018-11, with the labels that each got.

#312 Fix argument names in documentation
  MapboxDirections/MBLaneIndicationComponent.swift
  MapboxDirections/MBRoute.swift
  MapboxDirections/MBRouteLeg.swift
Labels: build, objective-c

#311 Coordinate Truncation
  MapboxDirections.xcodeproj/project.pbxproj
  MapboxDirections/Extensions/Double.swift
  MapboxDirections/MBDirectionsOptions.swift
  MapboxDirections/MBWaypoint.swift
  MapboxDirectionsTests/RouteOptionsTests.swift
Labels: TDD 🤖, bug

#314 No Response Fix
  MapboxDirections/MBDirections.swift
  MapboxDirectionsTests/DirectionsTests.swift
Labels: bug

#316 v0.25.1
  CHANGELOG.md
  Cartfile.resolved
  Directions Example/Info.plist
  MapboxDirections.swift.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/Example (Objective-C).xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/Example (Swift).xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections Mac.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections iOS.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections tvOS.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections watchOS.xcscheme
  MapboxDirections/Info.plist
  MapboxDirectionsTests/Info.plist
Labels: build

#317 Fix parameter documentation
  MapboxDirections/OfflineDirections.swift
Labels: build, documentation, objective-c
