Repository mapbox/mapbox-directions-swift, pull requests merged in 2019-12, with the labels that each got.

#394 Fix decoding of unrecognized visual instruction component types
  Sources/MapboxDirections/VisualInstructionComponent.swift
  Tests/MapboxDirectionsTests/VisualInstructionComponentTests.swift
Labels: bug

#393 Objective-C removal followups for navigation SDK compatibility
  CHANGELOG.md
  MapboxDirections.xcodeproj/project.pbxproj
  Sources/MapboxDirections/AttributeOptions.swift
  Sources/MapboxDirections/Directions.swift
  Sources/MapboxDirections/DirectionsOptions.swift
  Sources/MapboxDirections/DirectionsResult.swift
  Sources/MapboxDirections/Intersection.swift
  Sources/MapboxDirections/MapMatching/MapMatchingResponse.swift
  Sources/MapboxDirections/MapMatching/Match.swift
  Sources/MapboxDirections/MapMatching/MatchResponse.swift
  Sources/MapboxDirections/QuickLook.swift
  Sources/MapboxDirections/RoadClasses.swift
  Sources/MapboxDirections/Route.swift
  Sources/MapboxDirections/RouteLeg.swift
  Sources/MapboxDirections/RouteOptions.swift
  Sources/MapboxDirections/RouteResponse.swift
  Sources/MapboxDirections/RouteStep.swift
  Sources/MapboxDirections/VisualInstruction.swift
  Sources/MapboxDirections/VisualInstructionComponent.swift
  Sources/MapboxDirections/Waypoint.swift
  Tests/MapboxDirectionsTests/IntersectionTests.swift
  Tests/MapboxDirectionsTests/MatchTests.swift
  Tests/MapboxDirectionsTests/QuickLookTests.swift
  Tests/MapboxDirectionsTests/RouteStepTests.swift
  Tests/MapboxDirectionsTests/RouteTests.swift
  Tests/MapboxDirectionsTests/VisualInstructionComponentTests.swift
  Tests/MapboxDirectionsTests/WaypointTests.swift
Labels: backwards-incompatible, bug, refactor

#250 Serialize speed limit annotations
  CHANGELOG.md
  Directions Example/ViewController.swift
  MapboxDirections.xcodeproj/project.pbxproj
  Package.swift
  Sources/MapboxDirections/AttributeOptions.swift
  Sources/MapboxDirections/Extensions/Measurement.swift
  Sources/MapboxDirections/RouteLeg.swift
  Sources/MapboxDirections/RouteStep.swift
  Tests/MapboxDirectionsTests/AnnotationTests.swift
  Tests/MapboxDirectionsTests/Fixtures/v5/annotation.json
  Tests/MapboxDirectionsTests/RouteLegTests.swift
Labels: enhancement, ⚠️ DO NOT MERGE

#401 Fix decoding Vienna Convention–style speed limits
  Sources/MapboxDirections/RouteStep.swift
  Tests/MapboxDirectionsTests/AnnotationTests.swift
  Tests/MapboxDirectionsTests/RouteStepTests.swift
Labels: bug

#402 Fix round-tripping pronunciations
  Sources/MapboxDirections/RouteStep.swift
  Tests/MapboxDirectionsTests/RouteStepTests.swift
Labels: bug
