Repository mapbox/mapbox-directions-swift, pull requests merged in 2019-08, with the labels that each got.

#378 Include docset title and version in masthead
  docs/jazzy.yml
  docs/theme/templates/header.mustache
  scripts/document.sh
Labels: documentation, enhancement

#367 Add support for speed limits via maxspeed annotations.
  CHANGELOG.md
  Directions Example/ViewController.swift
  MapboxDirections.xcodeproj/project.pbxproj
  Sources/CMapboxDirections/include/MBAttribute.h
  Sources/MapboxDirections/MBRouteLeg.swift
  Sources/MapboxDirections/MBSpeedLimit.swift
  Tests/MapboxDirectionsTests/AnnotationTests.swift
Labels: enhancement

#379 Require iOS 10.0 et al.
  CHANGELOG.md
  MapboxDirections.swift.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
Labels: backwards-incompatible, build
