Repository mapbox/mapbox-directions-swift, pull requests merged in 2020-11, with the labels that each got.

#467 Add publish-documentation.sh for generating and publishing new documentation
  README.md
  scripts/document.sh
  scripts/publish-documentation.sh
Labels: build, documentation

#480 Fix error requesting route with silent waypoints and waypoint targets
  CHANGELOG.md
  Sources/MapboxDirections/RouteOptions.swift
Labels: bug, quick fix

#483 Remove public documentation about alert-related symbols
  CHANGELOG.md
  Sources/MapboxDirections/AdministrationRegion.swift
  Sources/MapboxDirections/Incident.swift
  Sources/MapboxDirections/Intersection.swift
  Sources/MapboxDirections/RestStop.swift
  Sources/MapboxDirections/RouteLeg.swift
  Sources/MapboxDirections/TollCollection.swift
Labels: documentation, release blocker

#487 Polyline v5.0.0
  Cartfile
  Cartfile.resolved
  MapboxDirections.podspec
  Package.resolved
  Package.swift
Labels: build

#488 Linux
  .circleci/config.yml
  CHANGELOG.md
  Cartfile.resolved
  Package.resolved
  Package.swift
  README.md
  Sources/MapboxDirections/Directions.swift
  Sources/MapboxDirections/DirectionsCredentials.swift
  Sources/MapboxDirections/DirectionsError.swift
  Sources/MapboxDirections/DirectionsOptions.swift
  Sources/MapboxDirections/DirectionsResult.swift
  Sources/MapboxDirections/Extensions/Codable.swift
  Sources/MapboxDirections/Extensions/CoreLocation.swift
  Sources/MapboxDirections/Extensions/GeoJSON.swift
  Sources/MapboxDirections/Extensions/HTTPURLResponse.swift
  Sources/MapboxDirections/Intersection.swift
  Sources/MapboxDirections/MapMatching/MapMatchingResponse.swift
  Sources/MapboxDirections/MapMatching/Match.swift
  Sources/MapboxDirections/MapMatching/MatchOptions.swift
  Sources/MapboxDirections/MapMatching/Tracepoint.swift
  Sources/MapboxDirections/OfflineDirections.swift
  Sources/MapboxDirections/Route.swift
  Sources/MapboxDirections/RouteLeg.swift
  Sources/MapboxDirections/RouteLegAttributes.swift
  Sources/MapboxDirections/RouteOptions.swift
  Sources/MapboxDirections/RouteRefreshResponse.swift
  Sources/MapboxDirections/RouteResponse.swift
  Sources/MapboxDirections/RouteStep.swift
  Sources/MapboxDirections/SpokenInstruction.swift
  Sources/MapboxDirections/VisualInstruction.swift
  Sources/MapboxDirections/VisualInstructionBanner.swift
  Sources/MapboxDirections/VisualInstructionComponent.swift
  Sources/MapboxDirections/Waypoint.swift
  Tests/MapboxDirectionsTests/AnnotationTests.swift
  Tests/MapboxDirectionsTests/DirectionsCredentialsTests.swift
  Tests/MapboxDirectionsTests/DirectionsErrorTests.swift
  Tests/MapboxDirectionsTests/DirectionsTests.swift
  Tests/MapboxDirectionsTests/Fixture.swift
  Tests/MapboxDirectionsTests/IntersectionTests.swift
  Tests/MapboxDirectionsTests/MatchOptionsTests.swift
  Tests/MapboxDirectionsTests/MatchTests.swift
  Tests/MapboxDirectionsTests/QuickLookTests.swift
  Tests/MapboxDirectionsTests/RouteLegTests.swift
  Tests/MapboxDirectionsTests/RouteOptionsTests.swift
  Tests/MapboxDirectionsTests/RouteRefreshTests.swift
  Tests/MapboxDirectionsTests/RouteResponseTests.swift
  Tests/MapboxDirectionsTests/RouteStepTests.swift
  Tests/MapboxDirectionsTests/RouteTests.swift
  Tests/MapboxDirectionsTests/SpokenInstructionTests.swift
  Tests/MapboxDirectionsTests/WalkingOptionsTests.swift
  Tests/MapboxDirectionsTests/WaypointTests.swift
  Tests/MapboxDirectionsTests/XCTestManifests.swift
Labels: build, enhancement

#492 Fix error decoding administrative region
  Sources/MapboxDirections/AdministrationRegion.swift
Labels: bug

#493 v1.1.0-rc.1
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build

#495 OHHTTPStubs v9.0.0
  Cartfile.private
  Cartfile.resolved
  Tests/MapboxDirectionsTests/AnnotationTests.swift
  Tests/MapboxDirectionsTests/DirectionsCredentialsTests.swift
  Tests/MapboxDirectionsTests/DirectionsTests.swift
  Tests/MapboxDirectionsTests/MatchTests.swift
  Tests/MapboxDirectionsTests/OfflineDirectionsTests.swift
  Tests/MapboxDirectionsTests/RoutableMatchTests.swift
  Tests/MapboxDirectionsTests/RouteRefreshTests.swift
  Tests/MapboxDirectionsTests/V5Tests.swift
  Tests/MapboxDirectionsTests/VisualInstructionTests.swift
Labels: build

#497 v1.1.0
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build

#501 v1.2.0-alpha.1
  CHANGELOG.md
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
  scripts/update-version.sh
Labels: build

#500 Add CaseIterable protocol conformance in CongestionLevel.
  CHANGELOG.md
  Sources/MapboxDirections/Congestion.swift
Labels: UI, iOS

#503 Linux SPM Build error
  .circleci/config.yml
Labels: Linux, build

#490 Removing Intersection.geometryIndex
  CHANGELOG.md
  Cartfile.resolved
  Sources/MapboxDirections/Intersection.swift
  Sources/MapboxDirections/RouteLeg.swift
  Sources/MapboxDirections/RouteStep.swift
Labels: enhancement, refactor, release blocker

#504 v1.2.0-alpha.2
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: documentation, quick fix
