Repository mapbox/mapbox-directions-swift, pull requests merged in 2020-09, with the labels that each got.

#449 Update Mapbox Directions to v0.33.2.
  CHANGELOG.md
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build

#420 Route Refresh
  CHANGELOG.md
  MapboxDirections.xcodeproj/project.pbxproj
  Sources/MapboxDirections/Directions.swift
  Sources/MapboxDirections/DirectionsError.swift
  Sources/MapboxDirections/MapMatching/MapMatchingResponse.swift
  Sources/MapboxDirections/RefreshedRoute.swift
  Sources/MapboxDirections/RouteLeg.swift
  Sources/MapboxDirections/RouteLegAttributes.swift
  Sources/MapboxDirections/RouteOptions.swift
  Sources/MapboxDirections/RouteRefreshResponse.swift
  Tests/MapboxDirectionsTests/Fixtures/RouteRefresh/incorrectRouteRefreshResponse.json
  Tests/MapboxDirectionsTests/Fixtures/RouteRefresh/routeRefreshResponse.json
  Tests/MapboxDirectionsTests/Fixtures/RouteRefresh/routeRefreshRoute.json
  Tests/MapboxDirectionsTests/RouteRefreshTests.swift
Labels: platform parity, refactor, release blocker

#458 v1.0.0-rc.2
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build

#461 Republicize DirectionsOptions.urlQueryItems
  CHANGELOG.md
  Sources/MapboxDirections/DirectionsOptions.swift
  Sources/MapboxDirections/RouteOptions.swift
Labels: bug, platform parity
