Repository mapbox/mapbox-directions-swift, pull requests merged in 2021-07, with the labels that each got.

#557 RouteOptions.alleyPriority, walkwayPriority, speed are now optional
  CHANGELOG.md
  Sources/MapboxDirections/DirectionsOptions.swift
  Sources/MapboxDirections/RouteOptions.swift
  Tests/MapboxDirectionsTests/DirectionsTests.swift
  Tests/MapboxDirectionsTests/WalkingOptionsTests.swift
Labels: backwards-incompatible, refactor

#559 v2.0.0-beta.6
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build

#560 Fix bug where leg source and destination are mismatched when route contains trackpoint or silent waypoint
  Sources/MapboxDirections/DirectionsResult.swift
Labels: bug, map matching, quick fix

#562 RouteIdentifier removing
  CHANGELOG.md
  Directions Example/ContentView.swift
  Sources/MapboxDirections/Directions.swift
  Sources/MapboxDirections/DirectionsResult.swift
  Sources/MapboxDirections/MapMatching/Match.swift
  Sources/MapboxDirections/Route.swift
  Sources/MapboxDirections/RouteResponse.swift
  Tests/MapboxDirectionsTests/AnnotationTests.swift
  Tests/MapboxDirectionsTests/MatchTests.swift
  Tests/MapboxDirectionsTests/RoutableMatchTests.swift
  Tests/MapboxDirectionsTests/V5Tests.swift
  Tests/MapboxDirectionsTests/VisualInstructionTests.swift
Labels: backwards-incompatible, refactor

#565 v2.0.0-beta.7
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build

#567 Fixed RouteStep.exitIndex parsing
  CHANGELOG.md
  Sources/MapboxDirections/RouteStep.swift
  Tests/MapboxDirectionsTests/RouteStepTests.swift
Labels: bug
