Repository mapbox/mapbox-directions-swift, pull requests merged in 2021-09, with the labels that each got.

#583 Waypoint snapping to a closed road
  CHANGELOG.md
  Sources/MapboxDirections/DirectionsOptions.swift
  Sources/MapboxDirections/Waypoint.swift
  Tests/MapboxDirectionsTests/WaypointTests.swift
Labels: enhancement, platform parity

#587 Fix segment indices
  CHANGELOG.md
  Sources/MapboxDirections/RouteLeg.swift
  Tests/MapboxDirectionsTests/RouteLegTests.swift
Labels: bug

#593 Raw coding keys for DirectionsOptions and its subclasses match the query parameter names
  Sources/MapboxDirections/DirectionsOptions.swift
  Sources/MapboxDirections/RouteOptions.swift
  Tests/MapboxDirectionsTests/RouteOptionsTests.swift
Labels: refactor

#599 Migrate Carthage-based builds back to jakeheis/SwiftCLI
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
Labels: build, backwards-incompatible, command line tool

#601 Fix publish docs script
  scripts/publish-documentation.sh
Labels: documentation
