Repository mapbox/mapbox-directions-swift, pull requests merged in 2021-04, with the labels that each got.

#529 Intersections indicate preferred lane usage
  CHANGELOG.md
  Sources/MapboxDirections/Intersection.swift
  Sources/MapboxDirections/Lane.swift
  Sources/MapboxDirections/VisualInstructionComponent.swift
  Tests/MapboxDirectionsTests/IntersectionTests.swift
  Tests/MapboxDirectionsTests/RouteStepTests.swift
  Tests/MapboxDirectionsTests/VisualInstructionComponentTests.swift
  Tests/MapboxDirectionsTests/VisualInstructionTests.swift
Labels: Core, enhancement, platform parity

#532 Fix VisualInstruction.component.lane type mismatch
  Sources/MapboxDirections/VisualInstructionComponent.swift
  Tests/MapboxDirectionsTests/VisualInstructionComponentTests.swift
Labels: bug

#533 v2.0.0-beta.2
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build

#535 Preferred lane direction is now a ManeuverDirection
  Sources/MapboxDirections/Intersection.swift
  Sources/MapboxDirections/Lane.swift
  Sources/MapboxDirections/LaneIndication.swift
  Sources/MapboxDirections/VisualInstructionComponent.swift
  Tests/MapboxDirectionsTests/IntersectionTests.swift
Labels: refactor

#536 v2.0.0-beta.3
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build
