Repository mapbox/mapbox-directions-swift, pull requests merged in 2022-01, with the labels that each got.

#572 Option added to command line tool for outputting Xcode-compatible GPX file
  Sources/MapboxDirectionsCLI/CodingOperation.swift
  Sources/MapboxDirectionsCLI/main.swift
Labels: improvement, command line tool

#634 Route refreshing
  CHANGELOG.md
  MapboxDirections.xcodeproj/project.pbxproj
  Sources/MapboxDirections/RouteRefreshResponse.swift
  Sources/MapboxDirections/RouteRefreshSource.swift
Labels: bug, Core

#586 Add documentation for MapboxDirectionsCLI tool
  CommandLineTool.md
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
Labels: documentation, command line tool

#642 v2.2.0
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build

#645 Update Mapbox Directions to `v2.3.0-beta.1`.
  CHANGELOG.md
  Cartfile.resolved
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections Mac.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections iOS.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections tvOS.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections watchOS.xcscheme
  Package.resolved
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
Labels: build
