Repository mapbox/mapbox-directions-swift, pull requests merged in 2022-04, with the labels that each got.

#673 Exposing `departAt` and `arriveBy` properties
  CHANGELOG.md
  Sources/MapboxDirections/RouteOptions.swift
  Tests/MapboxDirectionsTests/RouteOptionsTests.swift
Labels: feature

#677 Breaking changes flow
  .circleci/config.yml
  .gitignore
  scripts/update-baseline.sh
  scripts/update-version.sh
  swift-package-baseline/README.md
  swift-package-baseline/baseline.txt
  swift-package-baseline/breakage-allowlist-path.txt
Labels: op-ex

#576 Add fall back to Directions API request when no input file is specified
  CHANGELOG.md
  Sources/MapboxDirectionsCLI/CodingOperation.swift
  Sources/MapboxDirectionsCLI/main.swift
Labels: improvement, command line tool
