Repository mapbox/mapbox-directions-swift, pull requests merged in 2022-09, with the labels that each got.

#734 v2.7.0-rc.1
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
  swift-package-baseline/baseline.txt
Labels: build

#733 Support `current_geometry_index` in route refresh
  CHANGELOG.md
  MapboxDirections.xcodeproj/project.pbxproj
  Sources/MapboxDirections/Directions.swift
  Sources/MapboxDirections/RouteLeg.swift
  Sources/MapboxDirections/RouteRefreshResponse.swift
  Tests/MapboxDirectionsTests/Fixtures/RouteRefresh/partialRouteRefreshResponse.json
  Tests/MapboxDirectionsTests/RouteRefreshTests.swift
Labels: improvement, platform parity

#738 Add documentation to `RouteResponse` and `MapMatchingResponse`
  Sources/MapboxDirections/MapMatching/MapMatchingResponse.swift
  Sources/MapboxDirections/RouteResponse.swift
Labels: documentation

#736 Remove iOS 11 support.
  CHANGELOG.md
  Cartfile
  Cartfile.resolved
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/Example.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections Mac.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections iOS.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections tvOS.xcscheme
  MapboxDirections.xcodeproj/xcshareddata/xcschemes/MapboxDirections watchOS.xcscheme
  Package.resolved
  Package.swift
  README.md
Labels: build

#745 Add `Waypoint.layer` property
  CHANGELOG.md
  Sources/MapboxDirections/RouteOptions.swift
  Sources/MapboxDirections/Waypoint.swift
  Tests/MapboxDirectionsTests/RouteOptionsTests.swift
  Tests/MapboxDirectionsTests/WaypointTests.swift
Labels: platform parity, feature
