Repository mapbox/mapbox-directions-swift, pull requests merged in 2022-05, with the labels that each got.

#689 Add RestStop.name; fix macOS builds
  CHANGELOG.md
  Cartfile.resolved
  Package.resolved
  Sources/MapboxDirections/RestStop.swift
  Tests/MapboxDirectionsTests/AnnotationTests.swift
  Tests/MapboxDirectionsTests/OfflineDirectionsTests.swift
  Tests/MapboxDirectionsTests/RoutableMatchTests.swift
  Tests/MapboxDirectionsTests/V5Tests.swift
  Tests/MapboxDirectionsTests/VisualInstructionTests.swift
Labels: build, feature

#691 Add `TollCollection.name` property
  CHANGELOG.md
  Sources/MapboxDirections/TollCollection.swift
  Tests/MapboxDirectionsTests/IntersectionTests.swift
Labels: platform parity, feature

#682 Fix placement of changelog entry from PR merge
  CHANGELOG.md
Labels: documentation

#669 Foreign JSON members roundtrip
  CHANGELOG.md
  MapboxDirections.xcodeproj/project.pbxproj
  Sources/MapboxDirections/AdministrativeRegion.swift
  Sources/MapboxDirections/DirectionsResult.swift
  Sources/MapboxDirections/Extensions/ForeignMemberContainer.swift
  Sources/MapboxDirections/Incident.swift
  Sources/MapboxDirections/Intersection.swift
  Sources/MapboxDirections/Lane.swift
  Sources/MapboxDirections/MapMatching/MapMatchingResponse.swift
  Sources/MapboxDirections/MapMatching/Match.swift
  Sources/MapboxDirections/MapMatching/Tracepoint.swift
  Sources/MapboxDirections/RefreshedRoute.swift
  Sources/MapboxDirections/RestStop.swift
  Sources/MapboxDirections/RouteLeg.swift
  Sources/MapboxDirections/RouteLegAttributes.swift
  Sources/MapboxDirections/RouteRefreshResponse.swift
  Sources/MapboxDirections/RouteResponse.swift
  Sources/MapboxDirections/RouteStep.swift
  Sources/MapboxDirections/SilentWaypoint.swift
  Sources/MapboxDirections/SpokenInstruction.swift
  Sources/MapboxDirections/TollCollection.swift
  Sources/MapboxDirections/VisualInstruction.swift
  Sources/MapboxDirections/VisualInstructionBanner.swift
  Sources/MapboxDirections/Waypoint.swift
  Tests/MapboxDirectionsTests/Fixtures/Responses/RouteRefreshResponseWithForeignMembers.json
  Tests/MapboxDirectionsTests/Fixtures/Responses/RouteResponseWithForeignMembers.json
  Tests/MapboxDirectionsTests/ForeignMemberContainerTests.swift
  Tests/MapboxDirectionsTests/RouteStepTests.swift
  Tests/MapboxDirectionsTests/RouteTests.swift
Labels: Core, feature

#697 RouteStep encoding rounding
  CHANGELOG.md
  Sources/MapboxDirections/RouteStep.swift
  Tests/MapboxDirectionsTests/RouteStepTests.swift
Labels: bug

#698 v2.5.0
  Directions Example/Info.plist
  MapboxDirections.podspec
  MapboxDirections.xcodeproj/project.pbxproj
  README.md
  Sources/MapboxDirections/Info.plist
  Tests/MapboxDirectionsTests/Info.plist
  swift-package-baseline/baseline.txt
Labels: build

#694 Maximum Weight
  CHANGELOG.md
  Sources/MapboxDirections/RouteOptions.swift
  Tests/MapboxDirectionsTests/RouteOptionsTests.swift
Labels: feature
